---
title: "Teaching"
---

## University of Texas at Austin

### Spring 2026

- STA 235 - Data Science for Business Applications
  - [class 01 - Simple and Multiple Regression](sp_sta235_2026/week_01.qmd)
  - [class 02 - Error, Uncertainty and the Linear Model](sp_sta235_2026/week_02.qmd)
  - [class 03 - Regression Assumptions](sp_sta235_2026/week_03.qmd)
  - [class 04 - Categorical Variables](sp_sta235_2026/week_04.qmd)
  - [class 05 - Interactions](sp_sta235_2026/week_05.qmd)
  - [class 06 - Modeling nonlinear relationships](sp_sta235_2026/week_05.qmd)


### Fall 2025

- STA 235 - Data Science for Business Applications
  - [class 01 - Simple and Multiple Regression](fall_sta235_2025/week_01/week_01.qmd)
  - [class 02 - Categorical Variables](fall_sta235_2025/week_01/week_02.qmd)
  - [class 03 - Interactions](fall_sta235_2025/week_01/week_03.qmd)
  - [class 04 - Regression Assumptions](fall_sta235_2025/week_01/week_04.qmd)
  - [class 05 - Modeling nonlinear relationships](fall_sta235_2025/week_01/week_05.qmd)
  - [class 06 - Time Series Decomposition and Autoregression](fall_sta235_2025/week_01/week_06.qmd)
  - [class 07 - Model building for prediction](fall_sta235_2025/week_01/week_07.qmd)
  - [class 08 - Logistic Regression 1](fall_sta235_2025/week_01/week_08.qmd)
  - [class 09 - Logistic Regression 2](fall_sta235_2025/week_01/week_09.qmd)
  - [class 10 - Decision Trees](fall_sta235_2025/week_01/week_10.qmd)
  - [class 11 - Random Forest](fall_sta235_2025/week_01/week_11.qmd)
  - [class 12 - Building models for explanation](fall_sta235_2025/week_01/week_12.qmd)
  - [class 13 - Basic Causal Inference](fall_sta235_2025/week_01/week_13.qmd)
  - [class 14 - Natural experiments and RDD](fall_sta235_2025/week_01/week_14.qmd)

### Spring 2025

- STA 235 - Data Science for Business Applications

### Fall 2024

- STA 235 Honors - Data Science for Business Applications
  - [class 01 - Simple and Multiple Regression](class_01.qmd)
  - [class 02 - Categorical Variables and Interactions](class_02.qmd)
  - [class 03 - Regression assumptions and Outliers](class_03.qmd)
  - [class 04 - Modeling nonlinear relationships](class_04.qmd)
  - [class 05 - Time Series Decomposition and Autoregression](class_05.qmd)
  - [class 06 - Model Selection](class_06.qmd)
  - [class 07 - Logistic Regression](class_07.qmd)
  - [class 08 - Basic Causal Inference](class_08.qmd)
  - [class 09 - Randomized Control Trials](class_09.qmd)
  - [class 10 - Natural Experiments - Diff-in-Diff](class_10.qmd)
  - [class 11 - Natural Experiments -  RDD](class_11.qmd)

### Summer 2024

- STA 235 - Data Science for Business Applications

### Spring 2024

- STA 235 - Data Science for Business Applications

- STA 301 - Introduction to Data Science

### Fall 2023

- STA 235 - Data Science for Business Applications

- STA 301 - Introduction to Data Science

### Spring 2023

- STA 235 - Data Science for Business Applications

- STA 301 - Introduction to Data Science

### Fall 2022

- STA 301 - Introduction to Data Science

### Summer 2022

- STA 235 - Data Science for Business Application

### Fall 2022

- STA 235 - Data Science for Business Application 

## University of São Paulo

### Summer 2021

-  Introduction to Probability Theory

### Summer 2020

-  Introduction to Probability Theory
