<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>mastery_exam_a_review – Henrique Bolfarine</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-5b4ad623e5705c0698d39aec6f10cf02.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Henrique Bolfarine</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../about.html"> 
<span class="menu-text">Research</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../teaching.html"> 
<span class="menu-text">Teaching</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-full page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    
<!-- main -->
<main class="content column-page" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block"></header>




<section id="review-of-mastery-exam-a-grammar-conceptual-soundness-solutions" class="level1">
<h1>Review of Mastery Exam A — Grammar, Conceptual Soundness &amp; Solutions</h1>
<hr>
<section id="overall-assessment" class="level2">
<h2 class="anchored" data-anchor-id="overall-assessment">Overall Assessment</h2>
<p>The exam is well-structured and covers important topics in applied linear regression: categorical predictors, interaction terms, diagnostics, and influential points. The questions progress logically in difficulty. Below are itemized suggestions followed by a solutions guide.</p>
<hr>
</section>
<section id="grammar-clarity-suggestions" class="level2">
<h2 class="anchored" data-anchor-id="grammar-clarity-suggestions">Grammar &amp; Clarity Suggestions</h2>
<section id="introduction-preamble" class="level3">
<h3 class="anchored" data-anchor-id="introduction-preamble">Introduction / Preamble</h3>
<ul>
<li><strong>“data consist of five hundred paid subscribers”</strong> — grammatically correct (data as plural), but consider “The dataset consists of…” for clarity in a non-technical audience context.</li>
<li><strong>“Your job is to understand how different types of workouts, frequency, and experience affect calories burned.”</strong> — Clear. No change needed.</li>
<li>The variable descriptions could benefit from a consistent format. <code>workout.type</code> lists sub-types with dashes but the others do not. Consider aligning presentation.</li>
</ul>
<hr>
</section>
<section id="section-1-categorical-variables" class="level3">
<h3 class="anchored" data-anchor-id="section-1-categorical-variables">Section 1 — Categorical Variables</h3>
<p><strong>Question 1</strong></p>
<ul>
<li>The statement reads: <em>“the intercept value of 399.42 indicates the predicted calories burned during aerobic-focused exercise, with an experience of zero.”</em></li>
<li><strong>Conceptual note:</strong> This is correct. Cardio is the reference category and experience = 0 is the baseline. However, an experience level of 0 may not be a meaningful or realistic value. It would be worth noting this to students as a limitation of literal interpretation of the intercept.</li>
</ul>
<p><strong>Question 2</strong></p>
<ul>
<li><em>“(correct) For two subscribers performing the same workout type, a one-point increase in experience is associated with an expected difference of 534.63 calories burned.”</em>
<ul>
<li>Grammatically and conceptually <strong>correct</strong>. The phrase “expected difference” appropriately signals association rather than causation.</li>
</ul></li>
<li>The distractor <em>“Increasing a subscriber’s experience by one point causes them to burn 534.63 more calories independently of any other factors”</em> correctly introduces the causation fallacy — good pedagogical choice.</li>
<li><strong>Suggestion:</strong> Replace “independently of any other factors” with “regardless of workout type” to make the distractor more precise and directly contrast with the correct answer.</li>
</ul>
<p><strong>Question 3</strong></p>
<ul>
<li><em>“not supported: Yoga has no effect on burning calories simply because its coefficient is not statistically significant.”</em>
<ul>
<li>Conceptually <strong>correct</strong> to mark this as not supported — absence of evidence is not evidence of absence. Well done.</li>
</ul></li>
<li><em>“not supported: For two subscribers with the same experience level, performing High-Intensity Interval Training increases the number of calories burned compared to all other workout types.”</em>
<ul>
<li>Conceptually <strong>correct</strong> — HIIT has a positive and significant coefficient relative to Cardio, but Strength (972.93) &gt; HIIT (599.88), so HIIT does not outperform all workout types.</li>
</ul></li>
<li><em>“supported: Given the same experience level, we can conclude that strength based exercise burns more calories than HIIT compared to cardio workouts.”</em>
<ul>
<li><strong>Grammar issue:</strong> The phrasing “burns more calories than HIIT compared to cardio workouts” is ambiguous. It could be read as saying Strength &gt; HIIT relative to cardio, which is correct (972.93 &gt; 599.88 above baseline), but the sentence structure is confusing. Suggested revision: <em>“Given the same experience level, strength-based exercise is associated with more calories burned than both HIIT and cardio workouts.”</em></li>
</ul></li>
</ul>
<p><strong>Question 4 (Predictions)</strong></p>
<ul>
<li>The three numerical predictions are correct and verifiable:
<ul>
<li><code>399.42 + 534.63×3.5 + 972.93 = 3243.54</code> ✓</li>
<li><code>399.42 + 534.63×1.2 + 0 = 1040.97</code> ✓</li>
<li><code>399.42 + 534.63×2.0 − 158.13 = 1310.55</code> ✓ (minor rounding to 1310.538)</li>
</ul></li>
<li>No issues here.</li>
</ul>
<hr>
</section>
<section id="section-1-diagnostics-question-5" class="level3">
<h3 class="anchored" data-anchor-id="section-1-diagnostics-question-5">Section 1 — Diagnostics (Question 5)</h3>
<ul>
<li><em>“the linearity assumption appears to be satisfied since there is no visible trend in the residuals vs.&nbsp;fitted plot”</em>
<ul>
<li><strong>Conceptually sound.</strong> Small caveat: the Residuals vs.&nbsp;Fitted plot in the PDF actually shows a slight curve in the smoother — instructors may want to mention this as borderline rather than clearly satisfied.</li>
</ul></li>
<li><em>“equal variance appears to be an issue, as we can observe an uneven spread of the residuals”</em>
<ul>
<li><strong>Correct.</strong> The fan-shaped spread in both Residuals vs.&nbsp;Fitted and Scale-Location plots is consistent with heteroscedasticity.</li>
</ul></li>
<li><strong>Grammar issue:</strong> <em>“Finally, equal variance appears to be an issue”</em> — awkward. Suggested revision: <em>“Finally, the equal variance (homoscedasticity) assumption appears to be violated, as the residuals show increasing spread with larger fitted values.”</em></li>
</ul>
<hr>
</section>
<section id="section-2-interactions" class="level3">
<h3 class="anchored" data-anchor-id="section-2-interactions">Section 2 — Interactions</h3>
<p><strong>Question 6</strong></p>
<ul>
<li><em>“The main effect for frequency shows that for each additional cardio workout session, the estimated calories burned increase by 283.74.”</em>
<ul>
<li><strong>Conceptually correct.</strong> The main effect of frequency applies to the reference category (Cardio) when the interaction terms are included.</li>
</ul></li>
<li><em>“This coefficient is statistically significant so we can be confident that there is an effect in the population.”</em>
<ul>
<li><strong>Minor conceptual note:</strong> Statistical significance does not prove an effect exists; rather, it means the observed result is unlikely under the null hypothesis. Suggested revision: <em>“This coefficient is statistically significant, providing evidence of an association between frequency and calories burned for cardio workouts in the population.”</em></li>
</ul></li>
</ul>
<p><strong>Question 7</strong></p>
<ul>
<li><em>“(correct) When gym frequency is zero, there is no evidence of a difference between strength and cardio workouts.”</em>
<ul>
<li><strong>Correct.</strong> <code>workout.typeStrength</code> has p = 0.4743, so at frequency = 0, Strength and Cardio are not statistically distinguishable.</li>
</ul></li>
<li><em>“When gym frequency is zero, the differences between the various workouts are statistically significant.”</em>
<ul>
<li>Correctly labeled as incorrect — none of the workout type main effects are significant.</li>
</ul></li>
<li><em>“For two subscribers with the same gym attendance, the expected increase in calories burned is 99.49 if one opts for high-intensity training compared to cardio training.”</em>
<ul>
<li><strong>Conceptual issue:</strong> This is a misleading distractor. The 99.49 coefficient is the <strong>main effect</strong> of HIIT at frequency = 0, not a general expected difference for “the same gym attendance.” At any nonzero frequency, the difference depends on the interaction. The distractor could be improved to be more precise about what “same attendance” means in this context.</li>
</ul></li>
</ul>
<p><strong>Question 8 (Calorie Calculations)</strong></p>
<ul>
<li>HIIT: <code>(283.74 + 118.59) × 4 = 1649.32</code> ✓</li>
<li>Strength: <code>(283.74 + 207.69) × 4 = 1965.72</code> ✓</li>
<li>Yoga: <code>(283.74 − 41.65) × 4 = 1048.36</code> ✓</li>
<li>These represent the marginal effect of going from frequency = 0 to frequency = 4 for each workout type, which is a correct and sensible interpretation.</li>
</ul>
<p><strong>Question 9</strong></p>
<ul>
<li>The answer correctly identifies Strength as yielding the highest calorie burn per additional gym session, and correctly notes the yoga interaction is not statistically significant.</li>
<li><strong>Typo:</strong> <em>“hus, we cannot statistically distinguish…”</em> — should be <strong>“thus”</strong>.</li>
<li><strong>Suggestion:</strong> Add that for Cardio itself, the slope is 283.74 per session, so Yoga (242.09… wait, 283.74 − 41.65 = 242.09) should be presented for completeness in the comparison table.</li>
</ul>
<hr>
</section>
<section id="section-3-regression-assumptions" class="level3">
<h3 class="anchored" data-anchor-id="section-3-regression-assumptions">Section 3 — Regression Assumptions</h3>
<p><strong>Question 10</strong></p>
<ul>
<li>The diagnostic plots clearly show a funnel/fan shape in both Residuals vs.&nbsp;Fitted and Scale-Location plots, indicating <strong>heteroscedasticity (non-constant variance)</strong>. The Q-Q plot also shows heavy tails, suggesting a <strong>normality violation</strong> as well.</li>
<li>The correct answer listed is “Equal variance” — this is appropriate given the visual evidence.</li>
<li><strong>Suggestion:</strong> The question asks which assumption “does not seem to be met.” Since there appear to be violations of <em>both</em> equal variance and normality, the question would benefit from specifying: <em>“Which is the most visually apparent assumption violation?”</em> or listing both as correct.</li>
</ul>
<p><strong>Question 11</strong></p>
<ul>
<li><em>“we can use model3 for making predictions, although we must be careful when using it to evaluate the significance of the coefficients or to calculate prediction intervals.”</em>
<ul>
<li><strong>Conceptually sound.</strong> When heteroscedasticity is present, point predictions remain unbiased but standard errors (and thus inference) are compromised.</li>
</ul></li>
<li><em>“point A is an influential point and should be considered to be removed from the data.”</em>
<ul>
<li><strong>Conceptual caution:</strong> Recommending removal of influential points is debatable practice. A more careful statement would be: <em>“Point A has high leverage and high residual, making it influential. It should be investigated further — if it represents a data entry error or a genuinely anomalous case, removal may be justified.”</em> Automatically removing influential points without justification can introduce bias.</li>
</ul></li>
</ul>
<p><strong>Question 12</strong></p>
<ul>
<li>The characterization of A, B, C is correct:
<ul>
<li><strong>A</strong>: High residual (far from regression line vertically) + high leverage (extreme x value, low duration) → <strong>influential point</strong></li>
<li><strong>B</strong>: High residual + near the center of x distribution → <strong>outlier, low leverage</strong></li>
<li><strong>C</strong>: Close to regression line (low residual) + extreme x value → <strong>high leverage, not influential</strong></li>
</ul></li>
<li><strong>Grammar note:</strong> The labels are presented without full sentences, which is fine for a matching exercise.</li>
</ul>
<hr>
</section>
</section>
<section id="summary-of-key-issues" class="level2">
<h2 class="anchored" data-anchor-id="summary-of-key-issues">Summary of Key Issues</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 35%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>#</th>
<th>Type</th>
<th>Issue</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Q3</td>
<td>Grammar</td>
<td>“burns more calories than HIIT compared to cardio” is ambiguous</td>
</tr>
<tr class="even">
<td>Q5</td>
<td>Grammar</td>
<td>“equal variance appears to be an issue” is awkward</td>
</tr>
<tr class="odd">
<td>Q6</td>
<td>Conceptual</td>
<td>Overstates what statistical significance implies</td>
</tr>
<tr class="even">
<td>Q7</td>
<td>Conceptual</td>
<td>The 99.49 distractor would benefit from clearer framing</td>
</tr>
<tr class="odd">
<td>Q9</td>
<td>Typo</td>
<td>“hus” should be “thus”</td>
</tr>
<tr class="even">
<td>Q10</td>
<td>Conceptual</td>
<td>Normality also appears violated; question could acknowledge both</td>
</tr>
<tr class="odd">
<td>Q11</td>
<td>Conceptual</td>
<td>Influential point removal should be framed as investigation, not automatic removal</td>
</tr>
</tbody>
</table>
<hr>
</section>
<section id="complete-solutions-guide" class="level2">
<h2 class="anchored" data-anchor-id="complete-solutions-guide">Complete Solutions Guide</h2>
<section id="q1-intercept-interpretation" class="level3">
<h3 class="anchored" data-anchor-id="q1-intercept-interpretation">Q1 — Intercept Interpretation</h3>
<p>The intercept (399.42) represents the predicted calories burned for a subscriber performing a <strong>Cardio</strong> workout (the reference category) with an experience level of <strong>zero</strong>. It is the baseline from which all other estimates are measured.</p>
</section>
<section id="q2-experience-coefficient" class="level3">
<h3 class="anchored" data-anchor-id="q2-experience-coefficient">Q2 — Experience Coefficient</h3>
<p><strong>Correct answer:</strong> <em>For two subscribers performing the same workout type, a one-point increase in experience is associated with an expected difference of 534.63 calories burned.</em></p>
<p>This uses the language of association (not causation) and holds workout type constant — the two features that make it the correct interpretation of a regression coefficient.</p>
</section>
<section id="q3-workout-type-conclusions" class="level3">
<h3 class="anchored" data-anchor-id="q3-workout-type-conclusions">Q3 — Workout Type Conclusions</h3>
<ul>
<li>✅ <strong>Supported:</strong> Yoga vs.&nbsp;Cardio difference is not statistically significant (p = 0.0888 &gt; 0.05).</li>
<li>❌ <strong>Not supported:</strong> Non-significance ≠ no effect.</li>
<li>❌ <strong>Not supported:</strong> HIIT coefficient (599.88) &lt; Strength coefficient (972.93), so HIIT does not beat all workout types.</li>
<li>✅ <strong>Supported:</strong> Strength (972.93) &gt; HIIT (599.88), both relative to Cardio baseline.</li>
</ul>
</section>
<section id="q4-predictions" class="level3">
<h3 class="anchored" data-anchor-id="q4-predictions">Q4 — Predictions</h3>
<p>Using <code>ŷ = 399.42 + 534.63 × experience + β_workout</code>:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 32%">
<col style="width: 41%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Scenario</th>
<th>Calculation</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Experience = 3.5, Strength</td>
<td>399.42 + 534.63(3.5) + 972.93</td>
<td><strong>3243.54</strong></td>
</tr>
<tr class="even">
<td>Experience = 1.2, Cardio</td>
<td>399.42 + 534.63(1.2) + 0</td>
<td><strong>1040.97</strong></td>
</tr>
<tr class="odd">
<td>Experience = 2.0, Yoga</td>
<td>399.42 + 534.63(2.0) − 158.13</td>
<td><strong>1310.54</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="q5-diagnostic-plot-model1" class="level3">
<h3 class="anchored" data-anchor-id="q5-diagnostic-plot-model1">Q5 — Diagnostic Plot (model1)</h3>
<ul>
<li><strong>Linearity:</strong> Satisfied — no strong trend in Residuals vs.&nbsp;Fitted (borderline).</li>
<li><strong>Normality:</strong> Satisfied — points follow the Q-Q line reasonably well.</li>
<li><strong>Equal Variance:</strong> <strong>Violated</strong> — increasing spread of residuals with larger fitted values (heteroscedasticity).</li>
</ul>
</section>
<section id="q6-frequency-main-effect-model2" class="level3">
<h3 class="anchored" data-anchor-id="q6-frequency-main-effect-model2">Q6 — Frequency Main Effect (model2)</h3>
<p>283.74 calories per additional session applies to <strong>Cardio</strong> workouts specifically (the reference category). The coefficient is statistically significant (p &lt; 2e-16), providing strong evidence of a positive association between frequency and calories for cardio subscribers.</p>
</section>
<section id="q7-model2-conclusions" class="level3">
<h3 class="anchored" data-anchor-id="q7-model2-conclusions">Q7 — model2 Conclusions</h3>
<p><strong>Correct:</strong> When gym frequency is zero, there is no evidence of a difference between strength and cardio workouts (p = 0.4743).</p>
<p>The other options are wrong because: (a) all workout main effects are non-significant at frequency = 0; (b) the yoga coefficient confidence interval crosses zero; (c) 99.49 is the HIIT main effect at frequency = 0, not a general frequency-adjusted comparison.</p>
</section>
<section id="q8-calorie-effect-at-frequency-4" class="level3">
<h3 class="anchored" data-anchor-id="q8-calorie-effect-at-frequency-4">Q8 — Calorie Effect at Frequency = 4</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Workout</th>
<th>Slope</th>
<th>× 4</th>
<th>Calories</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Cardio</td>
<td>283.74</td>
<td>× 4</td>
<td>1134.96</td>
</tr>
<tr class="even">
<td>HIIT</td>
<td>283.74 + 118.59 = 402.33</td>
<td>× 4</td>
<td><strong>1649.32</strong></td>
</tr>
<tr class="odd">
<td>Strength</td>
<td>283.74 + 207.69 = 491.43</td>
<td>× 4</td>
<td><strong>1965.72</strong></td>
</tr>
<tr class="even">
<td>Yoga</td>
<td>283.74 − 41.65 = 242.09</td>
<td>× 4</td>
<td><strong>968.36</strong></td>
</tr>
</tbody>
</table>
</section>
<section id="q9-highestlowest-calorie-burn-by-frequency" class="level3">
<h3 class="anchored" data-anchor-id="q9-highestlowest-calorie-burn-by-frequency">Q9 — Highest/Lowest Calorie Burn by Frequency</h3>
<p><strong>Highest:</strong> Strength, at 491.43 calories per additional weekly session (interaction significant: CI [157.32, 258.05]). <strong>Lowest:</strong> Yoga, at 242.09 per session, though this interaction is <strong>not statistically significant</strong> (p = 0.1135; CI includes 0), so we cannot statistically distinguish the yoga slope from the cardio slope.</p>
</section>
<section id="q10-violated-assumption-in-model3" class="level3">
<h3 class="anchored" data-anchor-id="q10-violated-assumption-in-model3">Q10 — Violated Assumption in model3</h3>
<p><strong>Equal variance (homoscedasticity)</strong> is the most visually apparent violation — the Residuals vs.&nbsp;Fitted and Scale-Location plots show a pronounced fan shape. The Q-Q plot also suggests possible normality issues (heavy tails).</p>
</section>
<section id="q11-using-model3-for-predictions" class="level3">
<h3 class="anchored" data-anchor-id="q11-using-model3-for-predictions">Q11 — Using model3 for Predictions</h3>
<p>Model3 can still be used for <strong>point predictions</strong>, since OLS estimates remain unbiased under heteroscedasticity. However, <strong>hypothesis tests, confidence intervals, and prediction intervals</strong> are unreliable because they depend on correct standard errors. Point A (high residual + high leverage) is <strong>influential</strong> and warrants investigation before any decision about removal.</p>
</section>
<section id="q12-classifying-points-a-b-c" class="level3">
<h3 class="anchored" data-anchor-id="q12-classifying-points-a-b-c">Q12 — Classifying Points A, B, C</h3>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Point</th>
<th>Residual</th>
<th>Leverage</th>
<th>Classification</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>A</td>
<td>High</td>
<td>High</td>
<td>Influential point</td>
</tr>
<tr class="even">
<td>B</td>
<td>High</td>
<td>Low</td>
<td>Outlier (non-influential)</td>
</tr>
<tr class="odd">
<td>C</td>
<td>Low</td>
<td>High</td>
<td>High-leverage, not influential</td>
</tr>
</tbody>
</table>
<p>An influential point is one that substantially affects the fitted regression line. A has both high leverage (extreme x) and a large residual, so it “pulls” the line toward it. B is anomalous in y but sits in the middle of the x range, so it exerts less influence on the slope. C is far out in x but falls close to the regression line, so it reinforces rather than distorts the fit.</p>
<hr>
<p><em>Review prepared for Mastery Exam A — Henrique Bolfarine (referenced course material)</em></p>


</section>
</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>