<!DOCTYPE html>
<html lang="en"><head>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-html/tabby.min.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.6.42">

  <meta name="author" content="Class 01 - Linear Regression">
  <title>Henrique Bolfarine – Data Science for Business Applications</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
    /* CSS for syntax highlighting */
    pre > code.sourceCode { white-space: pre; position: relative; }
    pre > code.sourceCode > span { line-height: 1.25; }
    pre > code.sourceCode > span:empty { height: 1.2em; }
    .sourceCode { overflow: visible; }
    code.sourceCode > span { color: inherit; text-decoration: inherit; }
    div.sourceCode { margin: 1em 0; }
    pre.sourceCode { margin: 0; }
    @media screen {
    div.sourceCode { overflow: auto; }
    }
    @media print {
    pre > code.sourceCode { white-space: pre-wrap; }
    pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
    }
    pre.numberSource code
      { counter-reset: source-line 0; }
    pre.numberSource code > span
      { position: relative; left: -4em; counter-increment: source-line; }
    pre.numberSource code > span > a:first-child::before
      { content: counter(source-line);
        position: relative; left: -1em; text-align: right; vertical-align: baseline;
        border: none; display: inline-block;
        -webkit-touch-callout: none; -webkit-user-select: none;
        -khtml-user-select: none; -moz-user-select: none;
        -ms-user-select: none; user-select: none;
        padding: 0 4px; width: 4em;
        color: #aaaaaa;
      }
    pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
    div.sourceCode
      { color: #003b4f; background-color: #f1f3f5; }
    @media screen {
    pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
    }
    code span { color: #003b4f; } /* Normal */
    code span.al { color: #ad0000; } /* Alert */
    code span.an { color: #5e5e5e; } /* Annotation */
    code span.at { color: #657422; } /* Attribute */
    code span.bn { color: #ad0000; } /* BaseN */
    code span.bu { } /* BuiltIn */
    code span.cf { color: #003b4f; font-weight: bold; } /* ControlFlow */
    code span.ch { color: #20794d; } /* Char */
    code span.cn { color: #8f5902; } /* Constant */
    code span.co { color: #5e5e5e; } /* Comment */
    code span.cv { color: #5e5e5e; font-style: italic; } /* CommentVar */
    code span.do { color: #5e5e5e; font-style: italic; } /* Documentation */
    code span.dt { color: #ad0000; } /* DataType */
    code span.dv { color: #ad0000; } /* DecVal */
    code span.er { color: #ad0000; } /* Error */
    code span.ex { } /* Extension */
    code span.fl { color: #ad0000; } /* Float */
    code span.fu { color: #4758ab; } /* Function */
    code span.im { color: #00769e; } /* Import */
    code span.in { color: #5e5e5e; } /* Information */
    code span.kw { color: #003b4f; font-weight: bold; } /* Keyword */
    code span.op { color: #5e5e5e; } /* Operator */
    code span.ot { color: #003b4f; } /* Other */
    code span.pp { color: #ad0000; } /* Preprocessor */
    code span.sc { color: #5e5e5e; } /* SpecialChar */
    code span.ss { color: #20794d; } /* SpecialString */
    code span.st { color: #20794d; } /* String */
    code span.va { color: #111111; } /* Variable */
    code span.vs { color: #20794d; } /* VerbatimString */
    code span.wa { color: #5e5e5e; font-style: italic; } /* Warning */
  </style>
  <link rel="stylesheet" href="../../site_libs/revealjs/dist/theme/quarto-2f366650f320edcfcf53d73c80250a32.css">
  <link href="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/font-awesome/css/all.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/reveal-chalkboard/style.css" rel="stylesheet">
  <link href="../../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
  <style type="text/css">
  ul li ul li {
    font-size: 0.8em;
  }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section id="title-slide" data-background-image="week_01_docs/background_sta235h.png" class="quarto-title-block center">
  <h1 class="title">Data Science for Business Applications</h1>

<div class="quarto-title-authors">
<div class="quarto-title-author">
<div class="quarto-title-author-name">
Class 01 - Linear Regression 
</div>
</div>
</div>

</section><section id="TOC">
<nav role="doc-toc"> 
<h2 id="toc-title">Presentation Outline</h2>
<ul>
<li><a href="#/introduction" id="/toc-introduction">Introduction</a></li>
<li><a href="#/course-logistics" id="/toc-course-logistics">Course logistics</a></li>
<li><a href="#/simple-regression" id="/toc-simple-regression">Simple Regression</a></li>
<li><a href="#/multiple-regression" id="/toc-multiple-regression">Multiple Regression</a></li>
</ul>
</nav>
</section>
<section class="slide level2">

<!-- # ```{r load_apple_data, include=FALSE, cache=FALSE} -->
<!-- # apple <- read.csv("week_01_docs/apple_short.csv") -->
<!-- # options(digits = 4) -->
<!-- # ``` -->
</section>
<section>
<section id="introduction" class="title-slide slide level1 center">
<h1>Introduction</h1>

</section>
<section id="course-goals" class="slide level2">
<h2>Course Goals</h2>
<ul>
<li>Use regression to build predictive models</li>
<li>Understand the benefits and limitations of the models we build</li>
<li>Given a new business situation, select an appropriate model, build it, measure its effectiveness, and effectively communicate the results</li>
<li><span style="color: orange;"><strong>This is a practical course!</strong></span></li>
</ul>
<!-- ## What are time series? -->
<!-- -   Data where the cases represent time: data collected every day, month, year, etc. -->
<!-- -   Time series are important for both **explaining** how variables change over time and **forecasting** the future -->
<!-- -   Examples of time series data: -->
<!--     -   Google's closing daily stock price every day in 2020 -->
<!--     -   Inventory levels of each item at a retail store at the end of every week in 2020 -->
<!--     -   Apple's quarterly revenue since 2009 -->
</section>
<section id="why-does-this-course-exist" class="slide level2">
<h2>Why Does This Course Exist?</h2>
<ul>
<li>Why bother learning this stuff when we can get ChatGPT to do data analysis for us?</li>
<li>AI (and computing in general) is only useful when you have the expertise to be able to recognize the correctness (or not) of its output</li>
<li>In this class, you’ll develop that expertise!</li>
</ul>
</section>
<section id="about-the-course-staff" class="slide level2">
<h2>About the Course Staff</h2>
<ul>
<li><strong>Instructor:</strong> <strong>Henrique Bolfarine, Ph.D.</strong>
<ul>
<li><strong>Office hours:</strong> Mondays 1:00 PM - 2:00 PM (GSB 3.140 A)</li>
<li><strong>Email:</strong> <a href="mailto:henrique.bolfarine@austin.utexas.edu" class="email">henrique.bolfarine@austin.utexas.edu</a></li>
</ul></li>
<li><strong>Course Assistants:</strong>
<ul>
<li><strong>Lead Course Assistant (CA):</strong> Ezgi Durakoglugil</li>
<li><strong>Office hours:</strong> Many TA/CA office hours every week (both in person and on Zoom) - <strong>This should be your first option!</strong></li>
<li>You can ask any of the TAs/CAs about course content, but go to Ezgi for questions about logistics</li>
</ul></li>
</ul>
</section></section>
<section>
<section id="course-logistics" class="title-slide slide level1 center">
<h1>Course logistics</h1>

</section>
<section id="course-structure" class="slide level2">
<h2>Course Structure</h2>
<ul>
<li>Units
<ul>
<li><strong>Unit A:</strong> Fundamentals of regression modeling</li>
<li><strong>Unit B:</strong> Applications and extensions</li>
</ul></li>
<li>Canvas
<ul>
<li>Make sure you can log in and are enrolled in STA 235 in Canvas</li>
<li>Check out the home page for the weekly schedule and to meet the course staff</li>
</ul></li>
</ul>
</section>
<section id="statistical-computing" class="slide level2">
<h2>Statistical Computing</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>We will use <strong>R</strong> and <strong>RStudio</strong> for statistical analysis throughout the course</li>
<li>Make sure both are installed on your laptop and bring it to every class</li>
<li>If you aren’t comfortable with R/RStudio from STA 301, don’t worry!</li>
</ul>
</div><div class="column" style="width:30%;">
<p><img data-src="week_01_docs/R.png" style="width:100.0%"></p>
</div></div>
</section>
<section id="weekly-cadence-for-a-particular-topic" class="slide level2">
<h2>Weekly Cadence for a Particular Topic</h2>
<ul>
<li><strong>Due by the start of class on Monday/Tuesday:</strong> Perusall pre-class video/reading discussion covering the topic</li>
<li><strong>During class on Monday/Tuesday:</strong> Lecture, activities, practice topic</li>
<li><strong>Due by 11:59 PM the following Sunday/Monday:</strong> Homework covering the topic</li>
<li><strong>The following Monday/Tuesday: at the beginning of class:</strong> Checkpoint Quiz on that topic</li>
</ul>
</section>
<section id="pre-class-work" class="slide level2">
<h2>Pre-Class Work</h2>
<ul>
<li>This is a fast-paced course, so it’s essential that you think about the material before class.</li>
<li>We will use <strong>Perusall</strong> for pre-class video and reading assignments.</li>
<li>Use Perusall to ask your classmates questions, and share your knowledge, thoughts, and opinions.</li>
<li>This helps you better understand the material and will help me gear class time to what topics you are having the most trouble with.</li>
</ul>
</section>
<section id="pre-class-work-1" class="slide level2">
<h2>Pre-Class Work</h2>
<ul>
<li>Pre-class assignments (typically videos) are due at the start of each class.</li>
<li>Aim to chime in with at least a few thoughtful questions, responses, or comments for each reading assignment.</li>
<li>Grading is based on effort and thoughtfulness of your questions and comments and your engagement with classmates and the text.</li>
<li>Each assignment is scored 0-3, but with a reasonable effort you will get a 3 on each one (so don’t worry about your grade).</li>
</ul>
</section>
<section id="homework" class="slide level2">
<h2>Homework</h2>
<div class="columns">
<div class="column" style="width:60%;">
<ul>
<li>Why homework?</li>
<li>Homework is due each week <span style="color: red;"><strong>at 11:59 PM the night before class</strong></span> and submitted through Canvas.</li>
<li>Automatically graded; resubmit as many times as you want!</li>
<li>OK to work together, but try the problems on your own first for maximum benefit.</li>
</ul>
</div><div class="column" style="width:30%;">
<p><img data-src="week_01_docs/99problems.jpeg" style="width:100.0%"></p>
</div></div>
</section>
<section id="checkpoint-quizzes" class="slide level2">
<h2>Checkpoint Quizzes</h2>
<ul>
<li>It is critical in this course to stay on top of things and not fall behind.</li>
<li>Checkpoint Quiz at the <span style="color: red;"><strong>start of each class</strong></span> will help you ensure that you are really learning the material and give you an early heads-up if you aren’t.</li>
<li>We’ll drop your lowest quiz score from each unit (A and B).</li>
<li>You’ll have access to RStudio and a “cheat sheet” during quizzes (don’t spend time memorizing anything!).</li>
</ul>
</section>
<section id="mastery-exams" class="slide level2">
<h2>Mastery Exams</h2>
<ul>
<li>Each unit concludes with a Mastery Exam:
<ul>
<li><strong>Unit A:</strong> October 9 or 10 at 7 PM</li>
<li><strong>Unit B:</strong> University-assigned final exam period</li>
</ul></li>
<li>You’ll have access to RStudio and a “cheat sheet” during exams (don’t spend time memorizing anything!).</li>
</ul>
</section>
<section id="assessment-grading" class="slide level2">
<h2>Assessment Grading</h2>
<ul>
<li>Unit A has 7 Checkpoint Quizzes and Unit B has 6.</li>
<li>For each unit, we will replace your lowest quiz score with your exam score for that unit (if that helps your overall grade).</li>
</ul>
</section>
<section id="grading" class="slide level2">
<h2>Grading</h2>
<div class="center.smaller-text">
<table class="caption-top">
<thead>
<tr class="header">
<th>Component</th>
<th><strong>Points</strong></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pre-class work (Perusall)</td>
<td><strong>44</strong></td>
</tr>
<tr class="even">
<td>Class Participation</td>
<td><strong>56</strong></td>
</tr>
<tr class="odd">
<td>Homework (13)</td>
<td><strong>195</strong></td>
</tr>
<tr class="even">
<td>Checkpoint Quizze (13)</td>
<td><strong>325</strong></td>
</tr>
<tr class="odd">
<td>Exam A</td>
<td><strong>190</strong></td>
</tr>
<tr class="even">
<td>Exam B</td>
<td><strong>190</strong></td>
</tr>
<tr class="odd">
<td><strong>Total</strong></td>
<td><strong>1,000</strong></td>
</tr>
</tbody>
</table>
</div>
</section>
<section id="getting-help" class="slide level2">
<h2>Getting Help</h2>
<ul>
<li><strong>My office hours:</strong> Schedule on Canvas.</li>
<li><strong>TA/CA office hours:</strong> Schedule on Canvas.</li>
<li>Post questions in videos in <strong>Perusall</strong> (for questions about the course material).</li>
<li>Post questions in group chats in <strong>Perusall</strong> (for general questions about the course, or homework questions).</li>
<li>Weekly optional TA/CA-led review session (TBD).</li>
</ul>
</section></section>
<section>
<section id="simple-regression" class="title-slide slide level1 center">
<h1>Simple Regression</h1>

</section>
<section id="section" class="slide level2">
<h2></h2>
<div class="center">
<ul>
<li>What personal characteristics about an instructor do you think are predictive of the scores they receive on student evaluations?</li>
</ul>
</div>
<div class="center">
<p><img data-src="week_01_docs/hamermesh.png" style="width:100.0%"></p>
</div>
</section>
<section id="hamermesh-parker-2005-data-set" class="slide level2">
<h2>Hamermesh &amp; Parker (2005) Data Set</h2>
<div style="font-size: 0.8em;">
<ul>
<li>Student evaluations of <span class="math inline">\(N=463\)</span> instructors at UT Austin, 2000-2002</li>
<li>For each instructor:</li>
<li><code>eval</code>: average student evaluation of teacher</li>
<li><code>beauty</code>: average beauty score from a six-student panel</li>
<li><code>gender</code>: male or female</li>
<li><code>credits</code>: single- or multi-credit course</li>
<li><code>age</code>: age of instructor</li>
<li>(and more…)</li>
</ul>
</div>
</section>
<section id="explore-the-data-eval" class="slide level2">
<h2>Explore the data: <code>eval</code></h2>

<img data-src="week_01_files/figure-revealjs/plot1-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="explore-the-data-beauty" class="slide level2">
<h2>Explore the data: <code>beauty</code></h2>

<img data-src="week_01_files/figure-revealjs/plot2-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="explore-the-data" class="slide level2">
<h2>Explore the data</h2>

<img data-src="week_01_files/figure-revealjs/plot3-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="correlation" class="slide level2">
<h2>Correlation</h2>
<div class="center">
<p>The <strong>correlation</strong> <span class="math inline">\(r\)</span> between two variables <span class="math inline">\(X\)</span> and <span class="math inline">\(Y\)</span> measures the strength of the linear relationship between them. Correlation ranges from <span class="math inline">\(-1\)</span> (perfect negative relationship) to <span class="math inline">\(0\)</span> (no relationship) to <span class="math inline">\(1\)</span> (perfect positive relationship).</p>
</div>
</section>
<section id="correlation-1" class="slide level2">
<h2>Correlation</h2>

<img data-src="week_01_files/figure-revealjs/plot4-1.png" class="quarto-figure quarto-figure-center r-stretch" width="960"></section>
<section id="correlation-2" class="slide level2">
<h2>Correlation</h2>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a></a><span class="fu">cor</span>(profs<span class="sc">$</span>eval, profs<span class="sc">$</span>beauty)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1890391</code></pre>
</div>
</div>
<ul>
<li>How can we interpret this?</li>
<li>The <code>$</code> sign accesses the variables in the data set <code>profs.csv</code>.</li>
</ul>
</section>
<section id="lets-build-a-simple-regression-model" class="slide level2 smaller-text">
<h2>Let’s Build a Simple Regression Model</h2>
<div style="font-size: 0.8em;">
<p><span class="math display">\[
\text{eval} = \beta_0 + \beta_1 \cdot \text{beauty} + \epsilon
\]</span></p>
<ul>
<li><span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span> are known as coefficients (standard notations)</li>
<li><span class="math inline">\(\beta_0\)</span> is the intercept</li>
<li><span class="math inline">\(\beta_1\)</span> is the slope associated with <code>beauty</code></li>
<li>The term <span class="math inline">\(\epsilon\)</span> (epsilon) accounts for unobserved factors that are not included in this model</li>
</ul>
</div>
</section>
<section id="lets-build-a-simple-regression-model-in-rstudio" class="slide level2 smaller-text">
<h2>Let’s Build a Simple Regression Model in Rstudio</h2>
<div style="font-size: 0.8em;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a></a><span class="co"># Build a simple regression model</span></span>
<span id="cb3-2"><a></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(eval <span class="sc">~</span> beauty, <span class="at">data =</span> profs)</span>
<span id="cb3-3"><a></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = eval ~ beauty, data = profs)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.80015 -0.36304  0.07254  0.40207  1.10373 

Coefficients:
            Estimate Std. Error t value             Pr(&gt;|t|)    
(Intercept)  3.99827    0.02535 157.727 &lt; 0.0000000000000002 ***
beauty       0.13300    0.03218   4.133            0.0000425 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.5455 on 461 degrees of freedom
Multiple R-squared:  0.03574,   Adjusted R-squared:  0.03364 
F-statistic: 17.08 on 1 and 461 DF,  p-value: 0.00004247</code></pre>
</div>
</div>
</div>
</section>
<section id="interpreting-the-model" class="slide level2">
<h2>Interpreting the Model</h2>
<ul>
<li><p><code>eval</code> is the <strong>response</strong> variable (<span class="math inline">\(Y\)</span>); <code>beauty</code> is the <strong>predictor</strong> variable (<span class="math inline">\(X\)</span>).</p></li>
<li><p>Simple regression uses the best fit line to give us a linear equation to predict <span class="math inline">\(Y\)</span> from <span class="math inline">\(X\)</span>:</p>
<p><span class="math display">\[
\widehat{\text{eval}} = 3.998 + 0.133 \cdot \text{beauty}
\]</span></p></li>
<li><p>We can predict the evaluation score for someone based on their beauty score just by plugging into the equation.</p></li>
<li><p>What do the coefficients mean?</p></li>
</ul>
</section>
<section id="interpretation" class="slide level2">
<h2>Interpretation</h2>
<div style="font-size: 0.8em;">
<ul>
<li><strong>Intercept</strong>
<ul>
<li>When the beauty score is zero, the expected evaluation is <code>3.99</code> (almost 4).<br>
</li>
<li>Here, <code>beauty = 0</code> represents an “average beauty”.</li>
<li>Important, the intercept is evaluated always when the <strong>predictor</strong> variable is zero.</li>
</ul></li>
<li><strong>Slope for Beauty</strong>
<ul>
<li>For every one-unit increase in the beauty score, there is a <code>0.133</code> increase in the professor’s expected evaluation.<br>
</li>
<li>In this context, “expected” refers to the average evaluation.</li>
</ul></li>
</ul>
</div>
</section>
<section id="statistical-significance-of-the-model" class="slide level2">
<h2>Statistical Significance of the Model</h2>
<ul>
<li>The population regression line (the best fit line in the population) is <span class="math inline">\(Y = \beta_0 + \beta_1 X\)</span> (we can’t know this).</li>
<li>Our regression equation is the best fit line in the sample, or <span class="math inline">\(\hat{Y} = \hat{\beta}_0 + \hat{\beta}_1 X\)</span> (this is what we get from our sample data).</li>
<li>The sample intercept and slope <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> are our best estimates for the population intercept and slope <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>.</li>
<li>But we need to get a sense of how close <span class="math inline">\(\hat{\beta}_0\)</span> and <span class="math inline">\(\hat{\beta}_1\)</span> are to <span class="math inline">\(\beta_0\)</span> and <span class="math inline">\(\beta_1\)</span>!</li>
</ul>
</section>
<section id="p-values" class="slide level2">
<h2>P-values</h2>
<div style="font-size: 0.8em;">
<ul>
<li>For this model, the <strong>p-values</strong> associated with the coefficients, slope and intercept are close to zero:</li>
</ul>
<div class="center">
<table class="caption-top">
<thead>
<tr class="header">
<th>Term</th>
<th>p-value - <code>Pr(&gt;|t|)</code></th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>0.0000000000000002</td>
<td>***</td>
</tr>
<tr class="even">
<td>Beauty</td>
<td>0.0000425</td>
<td>***</td>
</tr>
</tbody>
</table>
</div>
<ul>
<li>In this case, there’s evidence that beauty has an impact on a professor’s evaluation at a populational level.</li>
<li>Thus, we can conclude that the effect of beauty is statistically significant in relation to the professor’s evaluation.</li>
</ul>
</div>
</section>
<section id="rule-of-thumb-for-p-values" class="slide level2">
<h2>Rule of Thumb for P-values</h2>
<div class="center">
<ul>
<li>If the p-value is smaller than 0.05, we can conclude that the effect is statistically significant.</li>
<li>Otherwise, if the p-value is greater than 0.05, we conclude that the effect from the predictor is not statistically significant.</li>
</ul>
</div>
</section>
<section id="confidence-intervals" class="slide level2">
<h2>Confidence Intervals</h2>
<div style="font-size: 0.7em;">
<p>Let’s get confidence intervals for the slope and intercept to get a sense of the uncertainty in our estimates:</p>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a></a><span class="fu">confint</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 2.5 %    97.5 %
(Intercept) 3.94845765 4.0480866
beauty      0.06976869 0.1962342</code></pre>
</div>
</div>
<ul>
<li><strong>Slope</strong>: We are 95% confident that the incremental impact of each additional beauty point is between <span class="math inline">\(0.07\)</span> and <span class="math inline">\(0.20\)</span> student evaluation points.</li>
<li><strong>Intercept</strong>: We are 95% confident that the average student evaluation score for average-looking professors (<code>beauty</code> = 0) is between <span class="math inline">\(3.95\)</span> and <span class="math inline">\(4.05\)</span>.</li>
<li><strong>Rule of thumb</strong>: If zero is inside the CI, the effect is not statistically significant.</li>
<li><strong>P-values</strong> and <strong>confidence intervals</strong> (CIs) are connected. If the p-value is greater than 0.05, it is likely that zero will be included within the confidence interval.</li>
</ul>
</div>
</section>
<section id="confidence-intervals-for-predictions" class="slide level2">
<h2>Confidence intervals for predictions</h2>
<div style="font-size: 0.8em;">
<ul>
<li><p>Interval for a single prediction:</p>
<ul>
<li>We are 95% confident that a <strong>single</strong> professor with a beauty score of 1 will get rated between 3.06 and 5.21.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a></a><span class="fu">predict</span>(model, <span class="fu">list</span>(<span class="at">beauty=</span><span class="dv">1</span>), <span class="at">interval=</span><span class="st">"prediction"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 4.131274 3.056375 5.206172</code></pre>
</div>
</div></li>
<li><p>Interval for an average prediction:</p>
<ul>
<li>We are 95% confident that the <strong>average</strong> rating of all professors with beauty scores of 1 will be between 4.05 and 4.21.</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a></a><span class="fu">predict</span>(model, <span class="fu">list</span>(<span class="at">beauty=</span><span class="dv">1</span>), <span class="at">interval=</span><span class="st">"confidence"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       fit      lwr      upr
1 4.131274 4.050776 4.211771</code></pre>
</div>
</div></li>
</ul>
</div>
</section>
<section id="residuals-and-r-squared" class="slide level2">
<h2>Residuals and R-squared</h2>
<div style="font-size: 0.8em;">
<ul>
<li>Each instructor has a <strong>residual</strong>: the difference between their actual and predicted scores (the <strong>prediction error</strong>).</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week_01_files/figure-revealjs/unnamed-chunk-6-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="residual-standard-error" class="slide level2">
<h2>Residual standard error</h2>
<div style="font-size: 0.8em;">
<ul>
<li>The residual standard error is in the same units as the response variable:
<ul>
<li>In this case the RSE is: <code>Residual standard error: 0.5455</code></li>
<li>All predictions made by this model will, on average, differ from the true values by approximately 0.5455, which represents one standard deviation of the residuals.</li>
</ul></li>
<li>We can even get the 95% prediction interval for a single (beauty = 1) prediction as
<ul>
<li>lower bound: <span class="math inline">\(3.998 + 0.133 \cdot 1 - 2\times \text{RSE}\)</span></li>
<li>upper bound: <span class="math inline">\(3.998 + 0.133 \cdot 1 + 2\times \text{RSE}\)</span></li>
</ul></li>
</ul>
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a></a><span class="co"># lower bound </span></span>
<span id="cb11-2"><a></a><span class="fl">3.998</span> <span class="sc">+</span> <span class="fl">0.133</span> <span class="sc">-</span> <span class="dv">2</span><span class="sc">*</span><span class="fl">0.5455</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 3.04</code></pre>
</div>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a></a><span class="co"># upper bound</span></span>
<span id="cb13-2"><a></a><span class="fl">3.998</span> <span class="sc">+</span> <span class="fl">0.133</span> <span class="sc">+</span> <span class="dv">2</span><span class="sc">*</span><span class="fl">0.5455</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 5.222</code></pre>
</div>
</div>
</div>
</section>
<section id="r-squared-r2" class="slide level2">
<h2>R-squared (<span class="math inline">\(R^2\)</span>)</h2>
<div style="font-size: 0.8em;">
<ul>
<li>The <span class="math inline">\(R^2\)</span> provides an understanding of the “fit” of the model in relation to the data.
<ul>
<li>If the <span class="math inline">\(R^2\)</span> is close to one, the model has a good fit.</li>
<li>If the <span class="math inline">\(R^2\)</span> is close to zero, the model does not provide a good fit for the data.</li>
<li><code>Multiple R-squared: 0.03574</code></li>
<li>This indicates not a great fit.</li>
</ul></li>
<li><strong>Important interpretation:</strong>
<ul>
<li>The <span class="math inline">\(R^2\)</span> represents the percentage of variation in the response variable that can be explained by the predictor.</li>
<li>For this model, 3.6% of the variation in evaluation scores can be explained by the beauty variable alone, while the remaining 96.4% is attributed to other unobserved factors.</li>
</ul></li>
</ul>
</div>
</section></section>
<section>
<section id="multiple-regression" class="title-slide slide level1 center">
<h1>Multiple Regression</h1>

</section>
<section id="adding-more-predictors" class="slide level2">
<h2>Adding more predictors</h2>
<div style="font-size: 0.8em;">
<ul>
<li>Is the professor’s evaluation explained only by it’s beauty or there might be other factor affecting their evalution?</li>
<li>Let’s check if the variable <code>age</code> might help us better explain the relationship between beauty and evaluation.</li>
<li>We update our model as:</li>
</ul>
<p><span class="math display">\[
\widehat{\text{eval}} = \beta_0 + \beta_1 \cdot \text{beauty} + \beta_2 \cdot \text{age} + \epsilon
\]</span> - We now have a multiple regression model. - Both <code>beauty</code> and <code>age</code> are numerical variables. - The term <span class="math inline">\(\epsilon\)</span> (epsilon) accounts for unobserved factors that are not included in this model.</p>
</div>
</section>
<section id="multiple-regression-model" class="slide level2">
<h2>Multiple regression model</h2>
<div style="font-size: 0.7em;">
<div class="cell" data-layout-align="center">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a></a><span class="co"># Build a simple regression model</span></span>
<span id="cb15-2"><a></a>model <span class="ot">&lt;-</span> <span class="fu">lm</span>(eval <span class="sc">~</span> beauty <span class="sc">+</span> age, <span class="at">data =</span> profs)</span>
<span id="cb15-3"><a></a><span class="fu">summary</span>(model)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = eval ~ beauty + age, data = profs)

Residuals:
     Min       1Q   Median       3Q      Max 
-1.80242 -0.36514  0.07407  0.39913  1.10206 

Coefficients:
             Estimate Std. Error t value             Pr(&gt;|t|)    
(Intercept) 3.9844013  0.1337296  29.794 &lt; 0.0000000000000002 ***
beauty      0.1340634  0.0337441   3.973            0.0000824 ***
age         0.0002868  0.0027148   0.106                0.916    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.546 on 460 degrees of freedom
Multiple R-squared:  0.03576,   Adjusted R-squared:  0.03157 
F-statistic:  8.53 on 2 and 460 DF,  p-value: 0.0002305</code></pre>
</div>
</div>
<ul>
<li>How can we interpret this model?</li>
</ul>
</div>
</section>
<section id="interpretation-of-model-coefficients" class="slide level2">
<h2>Interpretation of Model Coefficients</h2>
<div style="font-size: 0.8em;">
<ul>
<li><strong>Intercept</strong>
<ul>
<li>When both the beauty score and age are zero, the expected evaluation is <code>3.98</code> (almost 4).<br>
</li>
<li>Here, <code>beauty = 0</code> represents an “average beauty,” and <code>age = 0</code> is not meaningful in this context but is part of the model.<br>
</li>
<li>Important: The intercept is evaluated when <strong>all predictor variables</strong> (beauty and age) are zero.</li>
</ul></li>
<li><strong>Slope for Beauty</strong>
<ul>
<li>For every one-unit increase in the beauty score, there is a <code>0.134</code> increase in the professor’s expected evaluation, <strong>holding age constant</strong>.</li>
</ul></li>
<li><strong>Slope for Age</strong>
<ul>
<li>For every one-unit increase in age, there is a <code>0.0003</code> increase in the professor’s expected evaluation, <strong>holding beauty constant</strong>.<br>
</li>
</ul></li>
</ul>
</div>
</section>
<section id="statistical-significance" class="slide level2">
<h2>Statistical significance</h2>
<div style="font-size: 0.7em;">
<ul>
<li>For this model, the <strong>p-values</strong> associated with the coefficients (intercept, beauty, and age) are as follows:</li>
</ul>
<table class="caption-top">
<thead>
<tr class="header">
<th>Term</th>
<th>p-value - <code>Pr(&gt;|t|)</code></th>
<th>Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>&lt; 0.0000000000000002</td>
<td>***</td>
</tr>
<tr class="even">
<td>Beauty</td>
<td>0.0000824</td>
<td>***</td>
</tr>
<tr class="odd">
<td>Age</td>
<td>0.916</td>
<td></td>
</tr>
</tbody>
</table>
<ul>
<li>In this model, there is strong evidence that <code>beauty</code> has an impact on a professor’s evaluation at the population level, as its p-value is very close to zero.</li>
<li>However, the p-value for <code>age</code> (<code>0.916</code> &gt; 0.05) indicates that there is no statistically significant relationship between age and a professor’s evaluation.</li>
<li>Thus, we can conclude that the effect of <code>beauty</code> is statistically significant in relation to a professor’s evaluation, while the effect of <code>age</code> is not statistically significant.</li>
</ul>
</div>
</section>
<section id="rse-and-r2" class="slide level2">
<h2>RSE and <span class="math inline">\(R^2\)</span></h2>
<div style="font-size: 0.8em;">
<ul>
<li>There are no significant changes in relation to the RSE and <span class="math inline">\(R^2\)</span> in relation to the previous model.</li>
<li>This means that the quality of the fit and the accuracy of the predictions will be nearly identical to those of the previous model.</li>
<li>For this model, 3.6% of the variation in evaluation scores can be explained by the beauty and age variables alone, while the remaining 96.4% is attributed to other unobserved factors.</li>
<li>What about predictions and confidence intervals?</li>
</ul>
</div>
</section>
<section id="whats-the-impact-of-gender-on-student-evaluations" class="slide level2">
<h2>What’s the Impact of Gender on Student Evaluations?</h2>
<div style="font-size: 0.8em;">
<ul>
<li>Do you see a difference between men (blue) and women (red)?</li>
</ul>
<div class="cell" data-layout-align="center">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="week_01_files/figure-revealjs/unnamed-chunk-9-1.png" class="quarto-figure quarto-figure-center" width="960"></p>
</figure>
</div>
</div>
</div>
</div>
</section>
<section id="for-for-the-weekend" class="slide level2">
<h2>For for the Weekend</h2>
<ul>
<li>Read the syllabus.</li>
<li>Do the first homework assignment in Canvas (covering today’s material).</li>
<li>Do the first pre-class assignment in Perusall (to prepare for next week’s class).</li>
</ul>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="week_01_docs/texas_logo2.png" class="slide-logo"></p>
<div class="footer footer-default">

</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../../site_libs/revealjs/plugin/reveal-chalkboard/plugin.js"></script>
  <script src="../../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': true,
'previewLinksAuto': false,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleChalkboard(event)\"><kbd>b</kbd> Toggle Chalkboard</a></li>\n<li class=\"slide-tool-item\" data-item=\"6\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleNotesCanvas(event)\"><kbd>c</kbd> Toggle Notes Canvas</a></li>\n<li class=\"slide-tool-item\" data-item=\"7\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.downloadDrawings(event)\"><kbd>d</kbd> Download Drawings</a></li>\n<li class=\"slide-tool-item\" data-item=\"8\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'chalkboard': {"buttons":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: false,

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'linear',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'none',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'none',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, RevealChalkboard, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
    window.document.addEventListener("DOMContentLoaded", function (event) {
      const toggleBodyColorMode = (bsSheetEl) => {
        const mode = bsSheetEl.getAttribute("data-mode");
        const bodyEl = window.document.querySelector("body");
        if (mode === "dark") {
          bodyEl.classList.add("quarto-dark");
          bodyEl.classList.remove("quarto-light");
        } else {
          bodyEl.classList.add("quarto-light");
          bodyEl.classList.remove("quarto-dark");
        }
      }
      const toggleBodyColorPrimary = () => {
        const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
        if (bsSheetEl) {
          toggleBodyColorMode(bsSheetEl);
        }
      }
      toggleBodyColorPrimary();  
      const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
      tabsets.forEach(function(tabset) {
        const tabby = new Tabby('#' + tabset.id);
      });
      const isCodeAnnotation = (el) => {
        for (const clz of el.classList) {
          if (clz.startsWith('code-annotation-')) {                     
            return true;
          }
        }
        return false;
      }
      const onCopySuccess = function(e) {
        // button target
        const button = e.trigger;
        // don't keep focus
        button.blur();
        // flash "checked"
        button.classList.add('code-copy-button-checked');
        var currentTitle = button.getAttribute("title");
        button.setAttribute("title", "Copied!");
        let tooltip;
        if (window.bootstrap) {
          button.setAttribute("data-bs-toggle", "tooltip");
          button.setAttribute("data-bs-placement", "left");
          button.setAttribute("data-bs-title", "Copied!");
          tooltip = new bootstrap.Tooltip(button, 
            { trigger: "manual", 
              customClass: "code-copy-button-tooltip",
              offset: [0, -8]});
          tooltip.show();    
        }
        setTimeout(function() {
          if (tooltip) {
            tooltip.hide();
            button.removeAttribute("data-bs-title");
            button.removeAttribute("data-bs-toggle");
            button.removeAttribute("data-bs-placement");
          }
          button.setAttribute("title", currentTitle);
          button.classList.remove('code-copy-button-checked');
        }, 1000);
        // clear code selection
        e.clearSelection();
      }
      const getTextToCopy = function(trigger) {
          const codeEl = trigger.previousElementSibling.cloneNode(true);
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
      }
      const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
        text: getTextToCopy
      });
      clipboard.on('success', onCopySuccess);
      if (window.document.getElementById('quarto-embedded-source-code-modal')) {
        const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
          text: getTextToCopy,
          container: window.document.getElementById('quarto-embedded-source-code-modal')
        });
        clipboardModal.on('success', onCopySuccess);
      }
        var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
        var mailtoRegex = new RegExp(/^mailto:/);
          var filterRegex = new RegExp('/' + window.location.host + '/');
        var isInternal = (href) => {
            return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
        }
        // Inspect non-navigation links and adorn them if external
     	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
        for (var i=0; i<links.length; i++) {
          const link = links[i];
          if (!isInternal(link.href)) {
            // undo the damage that might have been done by quarto-nav.js in the case of
            // links that we want to consider external
            if (link.dataset.originalHref !== undefined) {
              link.href = link.dataset.originalHref;
            }
          }
        }
      function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
        const config = {
          allowHTML: true,
          maxWidth: 500,
          delay: 100,
          arrow: false,
          appendTo: function(el) {
              return el.closest('section.slide') || el.parentElement;
          },
          interactive: true,
          interactiveBorder: 10,
          theme: 'light-border',
          placement: 'bottom-start',
        };
        if (contentFn) {
          config.content = contentFn;
        }
        if (onTriggerFn) {
          config.onTrigger = onTriggerFn;
        }
        if (onUntriggerFn) {
          config.onUntrigger = onUntriggerFn;
        }
          config['offset'] = [0,0];
          config['maxWidth'] = 700;
        window.tippy(el, config); 
      }
      const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
      for (var i=0; i<noterefs.length; i++) {
        const ref = noterefs[i];
        tippyHover(ref, function() {
          // use id or data attribute instead here
          let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
          try { href = new URL(href).hash; } catch {}
          const id = href.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note) {
            return note.innerHTML;
          } else {
            return "";
          }
        });
      }
      const findCites = (el) => {
        const parentEl = el.parentElement;
        if (parentEl) {
          const cites = parentEl.dataset.cites;
          if (cites) {
            return {
              el,
              cites: cites.split(' ')
            };
          } else {
            return findCites(el.parentElement)
          }
        } else {
          return undefined;
        }
      };
      var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
      for (var i=0; i<bibliorefs.length; i++) {
        const ref = bibliorefs[i];
        const citeInfo = findCites(ref);
        if (citeInfo) {
          tippyHover(citeInfo.el, function() {
            var popup = window.document.createElement('div');
            citeInfo.cites.forEach(function(cite) {
              var citeDiv = window.document.createElement('div');
              citeDiv.classList.add('hanging-indent');
              citeDiv.classList.add('csl-entry');
              var biblioDiv = window.document.getElementById('ref-' + cite);
              if (biblioDiv) {
                citeDiv.innerHTML = biblioDiv.innerHTML;
              }
              popup.appendChild(citeDiv);
            });
            return popup.innerHTML;
          });
        }
      }
    });
    </script>
    

</body></html>